[package]
name = "project_m1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
image = "0.24.7"
screenshots = "0.8.6"
winit = "0.29.7"
display-info = "0.1.0"